version: "3.8"

services:
  app:
    image: django-full
    command: sh -c "./manage.py makemigrations && ./manage.py migrate && ./manage.py runsslserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    working_dir: /lock_database
    volumes:
      - ./:/lock_database
    depends_on:
      - db

  db:
    image: mysql:5.7
    volumes:
      - lock-mysql-data:/var/lib/mysql
    ports:
      - 3307:3306
    environment: 
      MYSQL_USER: 'django'
      MYSQL_PASSWORD: 'nRZ3AfHZcmhdXrRp'
      MYSQL_ROOT_PASSWORD: 'nRZ3AfHZcmhdXrRp'
      MYSQL_DATABASE: 'lock_database_db'
    restart: always

volumes:
  lock-mysql-data: