# Generated by Django 3.1.3 on 2021-01-13 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locks', '0002_auto_20201128_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='lock',
            name='image_link',
            field=models.URLField(null=True, verbose_name='Lock image link'),
        ),
    ]
